#!/usr/bin/env sh

set -ex
version="1.0"
srcdir=$(mktemp -d)
mkdir -p /var/lib/vkc/ /usr/share/vkc
curl -Ls -o /var/lib/vkc/vkc.jar "https://github.com/Kruhlmann/VirtKeyConduit/releases/download/$version/VirtKeyConduit.jar"
curl -Ls "https://github.com/Kruhlmann/VirtKeyConduit/archive/refs/tags/$version.tar.gz" | tar -xz -C "$srcdir"
test -d "/usr/share/vkc/keyboards" || mv "$srcdir/VirtKeyConduit-$version/keyboards" "/usr/share/vkc/keyboards"
cat > /usr/bin/vkc << EOF
#!/usr/bin/env sh
exec /usr/bin/java -jar '/var/lib/vkc/vkc.jar' "\$@"
EOF
chmod +x /usr/bin/vkc
echo "Installation complete."
